const NEW_MESSAGE = "NEW_MESSAGE";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const JOIN_ROOM = "JOIN_ROOM";
const LEAVE_ROOM = "LEAVE_ROOM";
const ONLINE_USERS = "ONLINE_USERS";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
const USER_STATUS_CHANGED = "USER_STATUS_CHANGED";

module.exports = {
    NEW_MESSAGE,
    NEW_MESSAGE_ALERT,
    JOIN_ROOM,
    LEAVE_ROOM,
    ONLINE_USERS,
    START_TYPING,
    STOP_TYPING,
    USER_STATUS_CHANGED
};
